### ISSUE TITLE
Handle CompressionType = "deflate shuffle"

### ISSUE THREAD

**Issue by ashiklom** [nasa/zarr-eosdis-store#5]
I have a NetCDF file that produced a `dmrpp` file with the following compressionType:

```xml
<dmrpp:chunks compressionType="deflate shuffle" byteOrder="LE">
```

This results in `EosdisStore` throwing an `Unrecognized CompressionType` error. Full traceback in "Details" below, but it's pretty clear and self-explanatory. Looks like you [already handle the `deflate` case](https://github.com/nasa/zarr-eosdis-store/blob/main/eosdis_store/dmrpp.py#L200-L206), but `dmrpp.py` needs to be revised to also handle the `deflate + shuffle` case.

The source file is the first `tavg1_2d_flx` file from [here](https://portal.nccs.nasa.gov/datashare/gmao/geos-fp/das/Y2020/M01/D01/) ([direct file link](https://portal.nccs.nasa.gov/datashare/gmao/geos-fp/das/Y2020/M01/D01/GEOS.fp.asm.tavg1_2d_flx_Nx.20200101_0030.V01.nc4)), with the `.dmrpp` created via the `mkdmrpp` script in this repo.

<details>

```
<ipython-input-20-c6dfcddf42b7> in <module>
----> 1 zfile = EosdisStore(netcdf, dmr_url=dmrpp)

~/miniconda3/envs/eisfire/lib/python3.9/site-packages/eosdis_store/stores.py in __init__(self, data_url, dmr_url)
    256         dmrpp = requests.get(dmr_url).text
    257         tree = ElementTree.fromstring(dmrpp)
--> 258         meta_store = to_zarr(tree)
    259         super(EosdisStore, self).__init__(meta_store, data_url)

~/miniconda3/envs/eisfire/lib/python3.9/site-packages/eosdis_store/dmrpp.py in to_zarr(root)
    277     zarr = {}
    278     dims = get_dimensions(root)
--> 279     zarr = group_to_zarr(root, dims)
    280     return zarr
    281

~/miniconda3/envs/eisfire/lib/python3.9/site-packages/eosdis_store/dmrpp.py in group_to_zarr(node, dims, prefix)
    245         # if this is an array, convert to zarr array
    246         if tag in TYPE_INFO:
--> 247             zarr_array = array_to_zarr(child, dims, prefix=prefix)
    248             zarr.update(zarr_array)
    249         # otherwise, if this is group or a Container Attribute - this has not been tested

~/miniconda3/envs/eisfire/lib/python3.9/site-packages/eosdis_store/dmrpp.py in array_to_zarr(node, dims, prefix)
    204                 zarray['compressor'] = None
    205             else:
--> 206                 raise Exception('Unrecognized compressionType: ' + compression)
    207             chunks = chunks_to_zarr(child)
    208             zarray.update(chunks['zarray'])

Exception: Unrecognized compressionType: deflate shuffle
```

</details>

**Comment by bilts** [comment]
This is fixed in v0.1.2, which was just published to pypi.  Thanks for the feedback!

**Comment by knutfrode** [comment]
Hi,

I am trying to follow some online examples, but e.g. this sample code
```
import zarr
from eosdis_store import EosdisStore

url = 'https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210715090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'

ds = zarr.open(EosdisStore(url))
```

produces an error
```
  File "/home/knutfd/mambaforge/envs/opendrift/lib/python3.11/site-packages/eosdis_store/dmrpp.py", line 210, in array_to_zarr
    raise Exception('Unrecognized compressionType: ' + compression)
Exception: Unrecognized compressionType: shuffle deflate
```

I installed eosdis_store (version 0.1.4) with `pip install zarr-eosdis-store` (inside a conda environment where zarr is aleady available, and from where I also need other libraries).

**Comment by knutfrode** [comment]
The error message says `shuffle deflate`, whereas in the code (dmrpp.py) it is called `deflate shuffle`
https://github.com/nasa/zarr-eosdis-store/blob/main/eosdis_store/dmrpp.py#L203
If I change this on line 203, it works.
